# 2. NumPy 배열
* NumPy에는 **ndarray**라는 데이터 타입의 배열이 사용된다.
* 같은 타입의 데이터만 저장할 수 있다.
* Python list에 비해 계산 속도가 빠르다.

In [1]:
import numpy as np

## 2-1. np.array() 함수로 생성하기

### 1차원 배열 생성하기

In [8]:
# 1차원 배열 생성하기
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [6]:
# type확인
type(arr)

numpy.ndarray

In [13]:
# array 함수에는 data에 1개만 들어가야 함
np.array(1, 2, 3, 4)

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [14]:
# 데이터 타입 확인
arr.dtype

dtype('int32')

In [18]:
# overflow 테스트
arr = np.array([2147483648, 0, 0, 0], dtype=np.int64)
arr

array([2147483648,          0,          0,          0], dtype=int64)

In [19]:
arr.dtype

dtype('int64')

In [23]:
arr = np.array([1, 2, 3, 4], dtype=np.float32)
arr

array([1., 2., 3., 4.], dtype=float32)

In [24]:
arr.dtype

dtype('float32')

In [25]:
# shape: 각 차원의 배열의 size(차원의 모양)
arr.shape

(4,)

In [26]:
# size: 배열 전체의 요소의 개수
arr.size

4

In [28]:
# ndim: 차원의 수
arr.ndim

1

In [29]:
# ndarray에는 같은 데이터 타입만 들어가야 함
arr = np.array([1, 2, 3, 3.14])
arr

array([1.  , 2.  , 3.  , 3.14])

In [33]:
# int, float -> int
arr = np.array([1, 2, 3, 3.14], dtype=np.int32)
arr

array([1, 2, 3, 3])

In [38]:
# int, float, str -> str
# >(big-endian), <(little-endian)
# 32-character string
arr = np.array([1, 2, 3, 3.14, "123456789012345678901234567890123"])
arr

array(['1', '2', '3', '3.14', '123456789012345678901234567890123'],
      dtype='<U33')

In [43]:
# 기존의 배열을 이용하여 타입이 다른 배열을 생성하기
new_arr = arr.astype(float)
new_arr

array([1.00000000e+00, 2.00000000e+00, 3.00000000e+00, 3.14000000e+00,
       1.23456789e+32])

In [44]:
arr.dtype, new_arr.dtype

(dtype('<U33'), dtype('float64'))

### 2-3. np.arange()

In [2]:
for i in range(1, 10, 2):
    print(i)

1
3
5
7
9


In [3]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

### 2-4. np.zeros()

In [19]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### 2-5. np.linspace()

In [16]:
np.linspace(1, 11)

array([ 1.        ,  1.20408163,  1.40816327,  1.6122449 ,  1.81632653,
        2.02040816,  2.2244898 ,  2.42857143,  2.63265306,  2.83673469,
        3.04081633,  3.24489796,  3.44897959,  3.65306122,  3.85714286,
        4.06122449,  4.26530612,  4.46938776,  4.67346939,  4.87755102,
        5.08163265,  5.28571429,  5.48979592,  5.69387755,  5.89795918,
        6.10204082,  6.30612245,  6.51020408,  6.71428571,  6.91836735,
        7.12244898,  7.32653061,  7.53061224,  7.73469388,  7.93877551,
        8.14285714,  8.34693878,  8.55102041,  8.75510204,  8.95918367,
        9.16326531,  9.36734694,  9.57142857,  9.7755102 ,  9.97959184,
       10.18367347, 10.3877551 , 10.59183673, 10.79591837, 11.        ])

### 2-6. np.full()

In [18]:
np.full((3, 4), 3)

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

### 2.7 np.eye()

In [4]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 2-8. np.random

In [5]:
np.random.rand(5)

array([0.70455386, 0.66389443, 0.52515066, 0.61697329, 0.4568286 ])

In [6]:
np.random.seed(123)
np.random.rand(2, 3)

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646]])

## 2-9. NumPy 배열 Save & Load

In [9]:
arr = np.arange(0, 5)  # 0~4
arr

array([0, 1, 2, 3, 4])

In [10]:
np.save('my_arr', arr)

In [13]:
new_arr = np.load('my_arr.npy')
new_arr

array([0, 1, 2, 3, 4])