# 4. 정렬

## 4-1. 1차원 배열

In [1]:
import numpy as np

In [2]:
np.random.seed(100)
arr = np.random.randint(1, 10, size=10)  # 1~9
arr

array([9, 9, 4, 8, 8, 1, 5, 3, 6, 3])

In [3]:
# 오름차순 정렬
np.sort(arr)

array([1, 3, 3, 4, 5, 6, 8, 8, 9, 9])

In [9]:
# 내림차순 정렬
np.sort(arr)[::-1]

array([9, 9, 8, 8, 6, 5, 4, 3, 3, 1])

In [10]:
arr

array([9, 9, 4, 8, 8, 1, 5, 3, 6, 3])

In [11]:
# 정렬 시 주의사항 (in-place)
arr.sort()

In [13]:
arr

array([1, 3, 3, 4, 5, 6, 8, 8, 9, 9])

## 4-2. 2차원 배열

In [18]:
np.random.seed(100)
arr2 = np.random.randint(1, 10, size=(3, 4))  # 1~9, size=(3, 4)
arr2

array([[9, 9, 4, 8],
       [8, 1, 5, 3],
       [6, 3, 3, 3]])

In [20]:
np.sort(arr2)  # sort(arr2, axis=1)과 동일

array([[4, 8, 9, 9],
       [1, 3, 5, 8],
       [3, 3, 3, 6]])

In [21]:
np.sort(arr2, axis=0)

array([[6, 1, 3, 3],
       [8, 3, 4, 3],
       [9, 9, 5, 8]])

In [22]:
arr2

array([[9, 9, 4, 8],
       [8, 1, 5, 3],
       [6, 3, 3, 3]])

In [23]:
# index를 반환하는 argsort
np.argsort(arr2)

array([[2, 3, 0, 1],
       [1, 3, 2, 0],
       [1, 2, 3, 0]])

In [24]:
np.argsort(arr2, axis=0)

array([[2, 1, 2, 1],
       [1, 2, 0, 2],
       [0, 0, 1, 0]])