# 5. 인덱싱과 슬라이싱

## 5-1. 인덱싱

In [3]:
import numpy as np

In [4]:
arr = np.arange(1, 11)  # 0~9
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[0], arr[4], arr[-1]

(1, 5, 10)

In [5]:
arr2 = np.arange(1, 13).reshape(3, 4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
arr2[0][1], arr2[1][2], arr2[2][3]

(2, 7, 12)

In [13]:
arr2[0, 1], arr2[1, 2], arr2[2, 3]  # numpy에서는 다차원 indexing

(2, 7, 12)

In [14]:
arr2[-1][-2]

11

## 5-2. 슬라이싱

### 1차원 배열

In [16]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
# 3~끝까지 슬라이싱 ([stsart:end:step])
arr[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
arr[2:5]

array([3, 4, 5])

In [20]:
# 처음-5까지 슬라이싱
arr[:5]

array([1, 2, 3, 4, 5])

In [21]:
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
# 슬라이싱을 한 후에 값을 변경하면 원본에 영향을 미칠까?
new_arr = arr[:5]
new_arr

array([1, 2, 3, 4, 5])

In [24]:
new_arr[0] = 100
new_arr

array([100,   2,   3,   4,   5])

In [25]:
arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [6]:
copy_arr = np.copy(arr)
copy_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 2차원 배열

In [7]:
arr2 = np.arange(1, 13).reshape(3, 4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
# 첫번째 행을 모두 가져오기
arr2[0], arr2[0, :]

(array([1, 2, 3, 4]), array([1, 2, 3, 4]))

In [9]:
# 세번째 열을 모두 가져오기
arr2[:, 2]

array([ 3,  7, 11])

In [13]:
# 첫번째, 두번째 행을 모두 가져오기
arr2[:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
# 두번째, 세번째 열을 모두 가져오기
arr2[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [16]:
# [[2, 3]
#  [6, 7]] 가져오기
arr2[0:2, 1:3]

array([[2, 3],
       [6, 7]])

## 5-3. Fancy 인덱싱

In [17]:
# 1차원 배열
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
# 1, 3, 5로 된 배열을 만들기
np.array([arr[0], arr[2], arr[4]])

array([1, 3, 5])

In [20]:
# 슬라이싱 [start:end:step]
arr[:5:2]

array([1, 3, 5])

In [21]:
# Fancy 인덱싱
arr[[0, 2, 4]]

array([1, 3, 5])

In [22]:
# 2차원 배열
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
# [[1, 2, 3, 4],
#  [9, 10, 11, 12]]
np.array([arr2[0], arr2[2]])

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [24]:
# Fancy 인덱싱
arr2[[0, 2]]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [25]:
# 주의
arr2[0, 2]  # arr2[0][2]

3

In [26]:
# 슬라이싱
arr2[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [27]:
# Fancy 인덱싱
arr2[:, [1, 2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

## 5-4. Boolean 인덱싱

In [28]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [30]:
# cond = [False, True, False, False, True]
arr[[False, True, False, False, True]]

array([1, 4])

In [31]:
arr > 2

array([False, False, False,  True,  True])

In [33]:
arr[arr > 2]

array([3, 4])

In [34]:
# 짝수만 뽑기
arr[arr%2 == 0]

array([0, 2, 4])

In [35]:
# 0, 3, 4
(arr<1) | (arr>2)

array([ True, False, False,  True,  True])

In [36]:
arr[(arr<1) | (arr>2)]

array([0, 3, 4])

In [37]:
# 2, 3
(arr>1) & (arr<4)

array([False, False,  True,  True, False])

In [38]:
arr[(arr>1) & (arr<4)]

array([2, 3])